/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/emission-factors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the emission factor catalogue */
        get: operations["listEmissionFactors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datapoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List ESRS datapoints (paginated) */
        get: operations["listDatapoints"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datapoints/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single datapoint by id */
        get: operations["getDatapoint"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/materiality/sectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List NACE Rev 2.1 sectors (sections + divisions) */
        get: operations["listNaceSectors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/materiality/catalogue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the industry-materiality catalogue rows */
        get: operations["listIndustryMateriality"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pillar-iii/tbls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the 10 EBA Pillar III ESG ITS templates with their state */
        get: operations["listPillarTbls"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Scope: "s1" | "s2" | "s3";
        /** @enum {string} */
        FactorSource: "MITECO" | "IDAE" | "DEFRA";
        /** @enum {string} */
        EsrsTopic: "E1" | "E2" | "E3" | "E4" | "E5" | "S1" | "S2" | "S3" | "S4" | "G1" | "GENERAL";
        EmissionFactor: {
            activityKey: string;
            scope: components["schemas"]["Scope"];
            category: string;
            subcategory?: string | null;
            activityLabel: string;
            /** @enum {string} */
            unit: "kgCO2e";
            efValue: number;
            efUnit: string;
            source: components["schemas"]["FactorSource"];
            sourceVersion?: string;
            year: number;
            region: string;
            citationUrl?: string;
            notes?: string;
        };
        /** @enum {string} */
        DatapointStatus: "live" | "partial" | "blocked" | "pending" | "not_material" | "custom";
        Datapoint: {
            id: string;
            efragId?: string;
            name: string;
            definition?: string;
            topic: components["schemas"]["EsrsTopic"];
            esrsDisclosure?: string;
            paragraph?: string;
            relatedAr?: string;
            /** @enum {string} */
            type: "numeric" | "percentage" | "monetary" | "text" | "boolean" | "date" | "enum";
            unit?: string;
            status: components["schemas"]["DatapointStatus"];
            mappings: {
                framework?: string;
                externalCode?: string;
                authoritative?: boolean;
            }[];
            crosswalk: ("SFDR" | "PILLAR_3" | "BENCHMARK" | "CLIMATE_LAW")[];
            /** @enum {integer} */
            phaseInYears?: 1 | 2 | 3;
            conditional: boolean;
            mayDisclose: boolean;
            voluntary: boolean;
            latestValue?: string;
            numericValue?: number;
            owner?: string;
            isCustom: boolean;
            tags: string[];
        };
        NaceSector: {
            code: string;
            /** @enum {string} */
            level: "section" | "division";
            parentCode: string | null;
            labelEs: string;
            labelEn: string;
        };
        IndustryMateriality: {
            sectorCode: string;
            scopeCategory: string;
            /** @enum {integer} */
            materiality: 0 | 1 | 2 | 3;
            /** @enum {string} */
            sourceFramework: "EFRAG_ESRS" | "SASB" | "GHG_Protocol" | "NFQ_internal";
            notes?: string | null;
        };
        TblTemplate: {
            num: number;
            code: string;
            title: string;
            summary?: string;
            /** @enum {string} */
            family: "transition" | "physical" | "taxonomy" | "mitigation";
            /** @enum {string} */
            status: "live" | "in_prep" | "methodology_gap" | "scheduled";
            datapointCount?: number;
            rowCount?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listEmissionFactors: {
        parameters: {
            query?: {
                scope?: components["schemas"]["Scope"];
                source?: components["schemas"]["FactorSource"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of emission factors */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmissionFactor"][];
                };
            };
        };
    };
    listDatapoints: {
        parameters: {
            query?: {
                topic?: components["schemas"]["EsrsTopic"];
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Datapoint list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Datapoint"][];
                        total: number;
                    };
                };
            };
        };
    };
    getDatapoint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Datapoint */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Datapoint"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listNaceSectors: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sector list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NaceSector"][];
                };
            };
        };
    };
    listIndustryMateriality: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Catalogue list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndustryMateriality"][];
                };
            };
        };
    };
    listPillarTbls: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TBL list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TblTemplate"][];
                };
            };
        };
    };
}
